# netlify.toml

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200


[build]
  command = "npm run build:ssr && npm run netlify:copy-server"
  publish = "dist/arealty/browser"

# 2. Serve robots.txt as plain text (prevents HTML syntax errors)
[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"

# 3. Optional: Add similar rules for sitemap.xml
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "text/xml"
    
# 1. Redirect all non-static requests to index.html for Angular routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

